version: 2
workflows:
  version: 2
  java_versions:
    jobs:
    - build-6
    - build-7
    - build-8

jobs:
  build-6:
    docker:
    - image: openjdk:6-jdk
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run: ./gradlew dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: ./gradlew test

  build-7:
    docker:
    - image: openjdk:7-jdk
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run: ./gradlew dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: ./gradlew test

  build-8:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run: ./gradlew dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: ./gradlew test

# Gradle 2.14 does not run on Java 9, and that's OK
#  build-9:
#    docker:
#    - image: circleci/openjdk:9-jdk
#    working_directory: ~/repo
#
#    environment:
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb
#
#    steps:
#    - checkout
#    - restore_cache:
#        keys:
#        - v1-dependencies-{{ checksum "build.gradle" }}
#        - v1-dependencies-
#    - run: gradle dependencies
#    - save_cache:
#        paths:
#        - ~/.gradle
#        key: v1-dependencies-{{ checksum "build.gradle" }}
#    - run: ./gradlew test
#
